### ISSUE TITLE
How would I use this?

### ISSUE THREAD

**Issue by fawfulthegreat** [uyjulian/PaperMarioModelViewer#2]
I would like to view Paper Mario models and I have dumps of both TTYD and SPM, however the instructions in the readme are confusing to me. I have the SFML thing, it's a bunch of files and none of them look like something I can install. Apologies if this sounds incredibly noobish, I literally made an account to ask for help on this because I found it on Google and it's really something I'm interested in. I just don't know what the first step to using this is.

**Comment by uyjulian** [comment]
This is an unfinished project, and it has a few issues, mainly, because textures have holes in them. I'm planning on writing a blender import plugin, but don't count on it since I'm busy doing something else.

This is source code, not something you can install on your computer. The instructions for compiling the code are written in `README.md`. By having SFML 2.1 installed on your computer I mean building and installing that library to the proper places.
